name: Workflow_disp Testing
        
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "staging"
      version:
        description: "Release version"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

